apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: rs94u7qok-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/rs94u7qok-java-springboot-gitops